#+TITLE: reFUNDScan
#+DESCRIPTION: Telegram/Discord bot to monitor on-chain activity for Cosmos-SDK Chains
#+STARTUP: inlineimages

* Table of Contents 
 - [[#capabilities][Capabilities]]
 - [[#run][Run]]
 - [[#configuration][Configuration]]
 - [[#build][Build]]

reFUNDScan is a tool used for tracking blockchain activity on Cosmos-SDK based chains, and sends those notifications 
to Telegram or Discord, or both! 

reFUNDScan is *extermely* configurable.

Want to track a specifc wallets' every action? You can do that!

Want to track all chain activity above a certain currency amount? Sure!

Want to block all transactions of a certain type, or that contain a certain address/keyword? Easy Peasy!

Want to send all chain activity to multiple channels, on multiple clients? You got it!

Want to name certain wallets for easier recognition? No issue!

The ~config.toml~ file generated by reFUNDScan is self documenting, and should be easy to understand. Here, you can
set many different parameters for enabling and disabling different types of messages, like delegations, transfers, etc.


** Capabilities
*** Current Features:
- Monitor blockchain activity
- Automatic Chain Configuration
- Multiple Currency Types
- Currency Limits
- ICNS Namings
- Explorer Tx/Account Hyperlinks
- Transaction Filtering
- Telegram/Discord support
- Send to multiple channels simultaneously
**** Transaction Support:
- Transfers
- IBC Transfers In/Out
- Delegations
- Undelegations
- Redelegations
- Rewards Withdrawal
- Comission Withdrawal
- REStake Transactions
**** Planned Support:
- Governence Votes
- Governence Progress
- Validator Creations
- Validator Edits
- Validator Status/Jailings
- Validator Unjails


** Run
reFUNDScan is built and tested with Linux x86/ARM. You can fetch a release on your platform with:
#+begin_src bash
wget https://github.com/refundvalidator/reFUNDScan/releases/download/v0.95/reFUNDScan-x86_64-linux.tar.gz
#+end_src

Then unpack the tarball:
#+begin_src
tar -xvf reFUNDScan-x86_64-linux.tar.gz && sudo mv reFUNDScan /usr/local/bin
#+end_src

Generate a ~config.toml~ for reFUNDScan to use (see below for configuration details):
#+begin_src bash
mkdir ~/.refundscan && reFUNDScan --init --config ~/.refundscan
#+end_src

Run the bot once configured, with the path to the config file:
#+begin_src bash
reFUNDScan --config ~/.refundscan
#+end_src

** Configuration
*** [clients] (required)
Here you set your clients, current clients are discord or telegram, both can be used a the same time.
You can also define multiple channels for each at once. You'll need to provide the Channel IDs for the channels
you wish to send to, and the bots' API keys for Discord and Telegram Respectively.
- [[https://www.siteguarding.com/en/how-to-get-telegram-bot-api-token][How to get Telegram API key]]
- [[https://www.siteguarding.com/en/how-to-get-telegram-bot-api-token][How to get Discord API key]]
- [[https://turbofuture.com/internet/Discord-Channel-ID][How to get Discord Channel-ID]]
*** [chain] (required)
reFUNDScan has the ability automatically configure itself, 
including puling Chain Info, RPC, and REST URLs, from the [[https://github.com/cosmos/chain-registry/tree/master][Cosmos Chain Registry]]  
just by being given a ~[chain]~ name. You'll want to ensure the name in this field is the EXACT same as the name defined in the chain registry.

*** [chaininfo]
Optionally set the bot to use manually-entered information for the chain.

*** [icns]
Optionally set the bot to use a manually-entered ICNS REST Url. 

*** [connections]
Optionally set the connection REST/Websocket URL's for the chain

*** [messages]
Here you can configure the events that triggers the messages to be sent to the channels,
as well as set the currency being used. (USD, EUR, etc.)

You can also set filters to allow/deny messages from being sent.

You can set a message type to ~whitelist~ mode to ONLY
allow messages that contain a certain phrase (like a name, addresses, words, etc.)
or you can set the message type to ~blacklist~ mode, to deny many messages that contain
those phrases.

There is also an ~amount-filter~ which will filter messages from sending that are 
below a certain currency threshold that you set. (like filtering all messages below $5)

*** [address]
In this section, you add any number of ~address.named~ fields you want, these will map custom
names for an address or validator address, for easier tracking.

** Build
reFUNDScan is open-source and can be easily run by anybody, the main channel is hosted at @reFUNDScan for the [[https://unification.com/][Unification]] Chain

To build the bot yourself simply clone the repo:
#+begin_src bash
git clone https://github.com/refundvalidator/reFUNDScan
#+end_src
Then run:
#+begin_src bash
cd reFUNDScan/src
#+end_src
Here, we can initialize our config file:
#+begin_src bash
go run . --init --config /folder/to/generate/config/
#+end_src
You'll need to set your Telegram/Discord Chat-IDs and APIs here, as well as the
Chains' name as it appears in the [[https://github.com/cosmos/chain-registry][Cosmos Chain Registry]]. 

After filling out the custom information, you can run it with:
#+begin_src bash
go run . --config /folder/containing/config/
#+end_src
Or you can compile the binary yourself
#+begin_src bash
go build -o refundscan .
./refundscan --config ~/.refundscan
#+end_src
Pre-compiled binaries can be found in the releases section of this repo

If using one of the binary releases, you can generate a config file with:
#+begin_src bash
./refundscan --init --config ~/folder/to/generate/config/
#+end_src
